image: gitlab/dind

services:
  - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

stages:
  - test
  - build_image_and_deploy

test:
  stage: test
  script:
    - docker build -t api-test -f Dockerfile.test .
    - docker run api-test

build_image_prod:
  stage: build_image_and_deploy
  script:
    - docker build -t registry.gitlab.com/bajanda/erp:prod .
    - docker push registry.gitlab.com/somosmascuba/erp:prod
  only:
    - master

build_image_staging:
  stage: build_image_and_deploy
  script:
    - docker build -t registry.gitlab.com/somosmascuba/erp:develop .
    - docker push registry.gitlab.com/somosmascuba/erp:develop
  only:
    - develop
