version: '3.7'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: management
      POSTGRES_USER: management
      POSTGRES_DB: postgres
      PG_DATA: /data
    ports:
      - 5432:5432
    volumes:
      - management-data:/data

volumes:
  management-data:
