FROM ubuntu:20.04

MAINTAINER Omar Antonio Diaz <tecnologia@somosmascuba.com.com>

ENV DJANGO_SETTINGS_MODULE manager.settings.live
ENV DEBIAN_FRONTEND noninteractive
ENV TZ Europe/Berlin

RUN apt-get update && apt-get upgrade -y

# Set the locale
RUN apt install -y locales
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8


RUN apt-get install -y  python3-dev \
    build-essential \
    apt-utils \
    python3-dev \
    gcc \
    libpq-dev \
    libffi-dev \
    zlib1g-dev \ 
    libssl-dev \
    libpcre3-dev \
    gettext \
    sudo \
    nginx \
    git \
    python3-venv \
    gettext

RUN mkdir -p /home/docker/src
RUN python3 -m venv /home/docker/venv

WORKDIR /home/docker/src

ADD . .

RUN . /home/docker/venv/bin/activate; \
      pip install -r /home/docker/src/requirements-test.txt;

CMD DJANGO_SETTINGS_MODULE=manager.settings.test /home/docker/venv/bin/pytest
