version: '3.7'

services:
  erp:
    image: registry.gitlab.com/bajanda/erp:prod
    dns:
      - 8.8.8.8
      - 9.9.9.9
    networks:
      - traefik
    environment:
      DJANGO_SETTINGS_MODULE: manager.settings.live
      MEDIA_URL: https://s3.amazonaws.com/somosmas-management/
      AWS_REGION: us-east-1
      AWS_S3_BUCKET_NAME: somosmas-management
      AWS_ACCESS_KEY_ID: AKIATJZEF4RNS7H4F72A
      DB_HOST: somosmas.crxyk3xu4oxe.us-east-1.rds.amazonaws.com
      DB_USER: postgres
      DB_NAME: erp
      EMAIL_HOST: smtp.sendgrid.net
      EMAIL_HOST_USER: apikey
      EMAIL_PORT: 25
      PAYPAL_MODE: live
      PAYPAL_CLIENT_ID: AXl-doaU57n9t8x1H0E2s05nDu4hFBuFXym8eMdmaRGgcnJXRMOOATsCh6wu3jpahpa0tLS-7XnJVdlD
      PAYPAL_CREATE_PRODUCT_URL: https://api.paypal.com/v1/catalogs/products
      PAYPAL_CREATE_PLAN_URL: https://api.paypal.com/v1/billing/plans
      REGISTRATION_DEFAULT_FROM_EMAIL: tecnologia@somosmascuba.com
      LC_ALL: es_ES.UTF-8
    deploy:
      replicas: 2
      labels:
        traefik.enable: 'true'
        traefik.http.services.erp.loadbalancer.server.port: '80'

        traefik.http.routers.erp-https.tls: 'true'
        traefik.http.routers.erp-https.rule: Host(`erp.somosmascuba.com`)
        traefik.http.routers.erp-https.entrypoints: https
        traefik.http.routers.erp-https.service: erp
        traefik.http.routers.erp-https.tls.certresolver: letsencrypt

        traefik.http.routers.erp-http.entrypoints: http
        traefik.http.routers.erp-http.rule: Host(`erp.somosmascuba.com`)
        traefik.http.routers.erp-http.service: erp
        traefik.http.routers.erp-http.middlewares: erp-https-redirect
        traefik.http.middlewares.erp-https-redirect.redirectscheme.scheme: https
    secrets:
      - ERP_AWS_SECRET_ACCESS_KEY
      - ERP_DB_PASSWORD
      - ERP_PAYPAL_CLIENT_SECRET
      - ERP_SENDGRID_API_KEY
      - ERP_RECAPTCHA_PUBLIC_KEY
      - ERP_RECAPTCHA_PRIVATE_KEY

secrets:
 ERP_AWS_SECRET_ACCESS_KEY:
   external: true
 ERP_DB_PASSWORD:
   external: true
 ERP_PAYPAL_CLIENT_SECRET:
   external: true
 ERP_SENDGRID_API_KEY:
   external: true
 ERP_RECAPTCHA_PUBLIC_KEY:
   external: true
 ERP_RECAPTCHA_PRIVATE_KEY:
   external: true

networks:
  traefik:
    external: true
