# Generated by Django 3.0.5 on 2020-04-24 18:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.FloatField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
