# Generated by Django 3.0.5 on 2020-05-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
