# Generated by Django 3.0.5 on 2020-05-09 10:15

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200506_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('criteria', picklefield.fields.PickledObjectField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
