# Generated by Django 3.0.6 on 2020-09-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200806_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massmail',
            name='criterias',
            field=models.ManyToManyField(blank=True, null=True, to='core.Criteria'),
        ),
    ]
