# Generated by Django 3.0.6 on 2020-09-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200902_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massmail',
            name='criterias',
            field=models.ManyToManyField(blank=True, to='core.Criteria'),
        ),
    ]
