# Generated by Django 3.0.6 on 2020-09-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200902_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='mass_mail',
        ),
        migrations.AddField(
            model_name='criteria',
            name='mass_mails',
            field=models.ManyToManyField(blank=True, to='core.MassMail'),
        ),
    ]
