# Generated by Django 3.0.6 on 2020-09-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200902_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='coordinator',
        ),
        migrations.AddField(
            model_name='club',
            name='coordinator_email',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
