# Generated by Django 3.0.6 on 2020-09-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200915_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='value',
            field=models.TextField(),
        ),
    ]
