# Generated by Django 3.0.6 on 2020-09-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200915_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='mass_mails',
        ),
    ]
