# Generated by Django 3.0.6 on 2020-10-12 16:46

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('concept', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('income', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
