- name: Update APT-Cache
  apt: update_cache=yes

- name: APT over HTTPS
  apt: 
    name: apt-transport-https

- name: Add the Docker PPA Key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D

- name: Add Docker repositories
  blockinfile:
    create: true
    dest: /etc/apt/sources.list.d/docker.list
    block: |
      deb https://apt.dockerproject.org/repo ubuntu-xenial main

- name: Install Ubuntu dependencies
  apt: 
    name: 
    - apt-transport-https
    - ca-certificates
    - linux-image-extra-virtual
    - docker.io
